### ISSUE TITLE
The "equal to" colour is ignored / defaults to black

### ISSUE THREAD

**Issue by ArPharazon** [tsansome/powerbi-databarkpivisual#3]
Found the following issue with the color for "Equal To":

![image](https://user-images.githubusercontent.com/177085/40463627-a783044c-5f59-11e8-8dc2-2e99dc757544.png)

Our target value = 120

when value = 119, colour changes to red  (correct)
when **value = 120**, colour changes to black  (incorrect / bug? - should be green as per the settings)
value = 121, colour changes to green (correct)

**Comment by Kailegh** [comment]
Is this solved? I see a commit that is supposed to fix that, but I have tried packaging it and importing it from a file in Power BI and I am still getting the same error

**Comment by tsansome** [comment]
Hi Kailegh, very sorry about this.

The issue has been fixed and will be included in the next update release. The update has been submitted, just waiting for the appsource team to bring it through. Once it's brought through I will post here

**Note**: I had not changed the GUID of the visual and that's why when you packaged and imported it it didn't work. 

thanks

**Comment by tsansome** [comment]
Hi all, this issue should be fixed as of the current release. Please update your visual, let me know if issue still persists

**Comment by Louis-Trilogy** [comment]
I recently downloaded this from the appstore within PowerBI and the bug is still persistent. I will try to get it from the web appstore and see if the version is different.

**Comment by Louis-Trilogy** [comment]
Version on the appstore still shows 1.0.0 updated 3/20/2018
